# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=128)),
                ('key_num', models.IntegerField()),
                ('scan_winfo', models.IntegerField()),
                ('result_winfo', models.IntegerField()),
                ('idea', models.IntegerField()),
                ('pv', models.IntegerField()),
                ('src', models.PositiveSmallIntegerField()),
                ('cmatch', models.PositiveSmallIntegerField()),
                ('stat_time', models.DateTimeField()),
                ('insert_time', models.DateTimeField()),
            ],
        ),
    ]
